apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kube-8aa5"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kube-8aa5"
  template:
    metadata:
      labels:
        app: "kube-8aa5"
    spec:
      containers:
        - name: "kube-8aa5"
          image: "docktest1.azurecr.io/kube"
          ports:
          - containerPort: 8080